"""Deterministic guide-centered variable-radius Gaussian support binding."""

from __future__ import annotations

from dataclasses import dataclass
import math
from numbers import Integral
from typing import Any

import numpy as np
from scipy.spatial import cKDTree
import torch

from .config import GuideGaussianFieldConfig


def _as_point_array(
    value: np.ndarray | torch.Tensor,
    *,
    name: str,
    require_unique: bool,
) -> np.ndarray:
    if isinstance(value, torch.Tensor):
        if value.ndim != 2 or int(value.shape[1]) != 3:
            raise ValueError(f"{name} must have shape [N, 3]")
        if not torch.is_floating_point(value) or value.is_complex():
            raise TypeError(f"{name} must be a real floating-point tensor")
        array = value.detach().cpu().numpy()
    else:
        array = np.asarray(value)
        if array.ndim != 2 or int(array.shape[1]) != 3:
            raise ValueError(f"{name} must have shape [N, 3]")
        if not np.issubdtype(array.dtype, np.floating):
            raise TypeError(f"{name} must be a real floating-point array")
    result = np.asarray(array, dtype=np.float64)
    if result.shape[0] == 0:
        raise ValueError(f"{name} must not be empty")
    if not np.isfinite(result).all():
        raise ValueError(f"{name} contains non-finite coordinates")
    if require_unique and np.unique(result, axis=0).shape[0] != result.shape[0]:
        raise ValueError(f"{name} contains duplicate points")
    return np.ascontiguousarray(result)


def _resolve_device_dtype(
    guide_points: np.ndarray | torch.Tensor,
    *,
    device: torch.device | str | None,
    dtype: torch.dtype | None,
) -> tuple[torch.device, torch.dtype]:
    if device is None and isinstance(guide_points, torch.Tensor):
        target_device = guide_points.device
    else:
        target_device = torch.device("cpu" if device is None else device)

    if dtype is None and isinstance(guide_points, torch.Tensor):
        target_dtype = guide_points.dtype
    else:
        target_dtype = torch.float32 if dtype is None else dtype
    if target_dtype not in (torch.float16, torch.float32, torch.float64):
        raise TypeError("dtype must be torch.float16, torch.float32, or torch.float64")
    return target_device, target_dtype


def _stable_unique_pairs(
    query_ids: np.ndarray,
    guide_ids: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    if query_ids.ndim != 1 or guide_ids.ndim != 1:
        raise ValueError("candidate pair arrays must be one-dimensional")
    if query_ids.shape != guide_ids.shape or query_ids.size == 0:
        raise ValueError("candidate pair arrays must be non-empty and shape-matched")
    order = np.lexsort((guide_ids, query_ids))
    sorted_query = np.asarray(query_ids[order], dtype=np.int64)
    sorted_guide = np.asarray(guide_ids[order], dtype=np.int64)
    keep = np.ones(sorted_query.shape[0], dtype=bool)
    if keep.size > 1:
        keep[1:] = (sorted_query[1:] != sorted_query[:-1]) | (
            sorted_guide[1:] != sorted_guide[:-1]
        )
    return sorted_query[keep], sorted_guide[keep]


@dataclass(frozen=True)
class GuideGaussianBinding:
    """Fixed geometry and CSR candidate pattern for guide Gaussian weights."""

    guide_points: torch.Tensor
    query_points: torch.Tensor
    reference_sigma: torch.Tensor
    row_ptr: torch.Tensor
    guide_ids: torch.Tensor
    query_ids: torch.Tensor
    report: dict[str, Any]
    config: GuideGaussianFieldConfig | None = None


def initialize_guide_gaussian_binding(
    guide_points: np.ndarray | torch.Tensor,
    query_points: np.ndarray | torch.Tensor,
    config: GuideGaussianFieldConfig | None = None,
    *,
    device: torch.device | str | None = None,
    dtype: torch.dtype | None = None,
) -> GuideGaussianBinding:
    """Build a fixed, fully covered guide-to-query candidate CSR.

    Guide spacing is measured with a guide KD-tree.  Candidate pairs are
    generated by a query KD-tree using one radius per guide, then stably
    sorted by ``(query_id, guide_id)``.  No candidate is padded, truncated,
    or replaced by a fallback.
    """

    cfg = GuideGaussianFieldConfig() if config is None else config
    if not isinstance(cfg, GuideGaussianFieldConfig):
        raise TypeError("config must be GuideGaussianFieldConfig")
    guide_np = _as_point_array(
        guide_points,
        name="guide_points",
        require_unique=True,
    )
    query_np = _as_point_array(
        query_points,
        name="query_points",
        require_unique=False,
    )
    guide_count = int(guide_np.shape[0])
    query_count = int(query_np.shape[0])
    if guide_count <= int(cfg.neighbor_count):
        raise ValueError(
            "guide_points must contain more points than neighbor_count to define spacing"
        )

    guide_tree = cKDTree(guide_np)
    neighbor_width = int(cfg.neighbor_count) + 1
    distances, neighbor_ids = guide_tree.query(
        guide_np,
        k=neighbor_width,
        workers=1,
    )
    distances = np.asarray(distances, dtype=np.float64)
    neighbor_ids = np.asarray(neighbor_ids, dtype=np.int64)
    if distances.shape != (guide_count, neighbor_width):
        raise RuntimeError("guide KD-tree returned an invalid neighbor shape")

    spacing = np.empty((guide_count,), dtype=np.float64)
    for guide_id in range(guide_count):
        row_distances = distances[guide_id]
        row_ids = neighbor_ids[guide_id]
        non_self = row_ids != guide_id
        row_distances = row_distances[non_self]
        row_ids = row_ids[non_self]
        order = np.lexsort((row_ids, row_distances))
        if order.size < int(cfg.neighbor_count):
            raise RuntimeError(
                f"guide {guide_id} has fewer than neighbor_count non-self neighbors"
            )
        selected_spacing = float(row_distances[order[int(cfg.neighbor_count) - 1]])
        if not math.isfinite(selected_spacing) or selected_spacing <= 0.0:
            raise ValueError(
                f"guide {guide_id} has non-finite or non-positive reference spacing"
            )
        spacing[guide_id] = selected_spacing

    reference_sigma = spacing / float(cfg.support_sigma)
    if not np.isfinite(reference_sigma).all() or np.any(reference_sigma <= 0.0):
        raise RuntimeError("reference_sigma must be finite and positive")

    query_tree = cKDTree(query_np)
    query_chunks: list[np.ndarray] = []
    guide_chunks: list[np.ndarray] = []
    candidate_radii = (
        float(cfg.support_sigma)
        * float(cfg.max_scale_ratio)
        * reference_sigma
    )
    for guide_id, radius in enumerate(candidate_radii.tolist()):
        if not math.isfinite(radius) or radius <= 0.0:
            raise RuntimeError(f"guide {guide_id} has an invalid candidate radius")
        candidates = np.asarray(
            query_tree.query_ball_point(guide_np[guide_id], radius),
            dtype=np.int64,
        )
        if candidates.size == 0:
            raise RuntimeError(f"query coverage has no candidates for guide {guide_id}")
        candidates.sort(kind="stable")
        query_chunks.append(candidates)
        guide_chunks.append(
            np.full(candidates.shape, guide_id, dtype=np.int64)
        )

    candidate_query_ids, candidate_guide_ids = _stable_unique_pairs(
        np.concatenate(query_chunks),
        np.concatenate(guide_chunks),
    )
    if candidate_query_ids.size == 0:
        raise RuntimeError("candidate CSR is empty")
    if candidate_query_ids.min() < 0 or candidate_query_ids.max() >= query_count:
        raise RuntimeError("candidate query IDs are out of range")
    if candidate_guide_ids.min() < 0 or candidate_guide_ids.max() >= guide_count:
        raise RuntimeError("candidate guide IDs are out of range")

    row_counts = np.bincount(candidate_query_ids, minlength=query_count).astype(
        np.int64,
        copy=False,
    )
    if row_counts.shape != (query_count,) or np.any(row_counts <= 0):
        uncovered = np.flatnonzero(row_counts <= 0)
        raise RuntimeError(
            "candidate CSR leaves queries uncovered: "
            f"{uncovered[:8].tolist()}"
        )
    row_ptr_np = np.empty((query_count + 1,), dtype=np.int64)
    row_ptr_np[0] = 0
    np.cumsum(row_counts, out=row_ptr_np[1:])
    if int(row_ptr_np[-1]) != int(candidate_query_ids.size):
        raise RuntimeError("CSR row pointer does not cover all candidate pairs")

    target_device, target_dtype = _resolve_device_dtype(
        guide_points,
        device=device,
        dtype=dtype,
    )
    guide_tensor = torch.as_tensor(
        guide_np,
        device=target_device,
        dtype=target_dtype,
    ).clone()
    query_tensor = torch.as_tensor(
        query_np,
        device=target_device,
        dtype=target_dtype,
    ).clone()
    report: dict[str, Any] = {
        "guide_count": guide_count,
        "query_count": query_count,
        "candidate_pair_count": int(candidate_query_ids.size),
        "neighbor_count": int(cfg.neighbor_count),
        "support_sigma": float(cfg.support_sigma),
        "max_candidate_radius_min": float(candidate_radii.min()),
        "max_candidate_radius_max": float(candidate_radii.max()),
        "reference_sigma_min": float(reference_sigma.min()),
        "reference_sigma_max": float(reference_sigma.max()),
        "candidate_count_min": int(row_counts.min()),
        "candidate_count_max": int(row_counts.max()),
        "candidate_count_mean": float(row_counts.mean()),
        "all_queries_covered": True,
        "stable_pair_order": True,
        "duplicate_pairs_removed": int(
            sum(chunk.size for chunk in query_chunks) - candidate_query_ids.size
        ),
        "fallback_used": False,
        "config": cfg.to_json_dict(),
        "device": str(target_device),
        "dtype": str(target_dtype),
    }
    return GuideGaussianBinding(
        guide_points=guide_tensor,
        query_points=query_tensor,
        reference_sigma=torch.as_tensor(
            reference_sigma,
            device=target_device,
            dtype=target_dtype,
        ).clone(),
        row_ptr=torch.as_tensor(
            row_ptr_np,
            device=target_device,
            dtype=torch.long,
        ).clone(),
        guide_ids=torch.as_tensor(
            candidate_guide_ids,
            device=target_device,
            dtype=torch.long,
        ).clone(),
        query_ids=torch.as_tensor(
            candidate_query_ids,
            device=target_device,
            dtype=torch.long,
        ).clone(),
        report=report,
        config=cfg,
    )
