"""Differentiable grooming primitives for AniGroom."""

from .geometry_residuals import (
    DecodedGeometryResiduals,
    RenderGeometryResidualField,
    apply_asinh_logit_residual,
    apply_asinh_log_ratio_residual,
    apply_direction_residual,
    apply_log_ratio_residual,
    direction_to_local_components,
    fourth_moment_norm,
    encode_asinh_logit_residual,
    length_residual_prior_coordinate,
    local_components_to_world,
    population_stable_residual_norm,
    tail_concentration_residual_loss,
    vector_to_local_components,
)
from .gaussian_rgb_residual import GaussianRGBResidualField

from .strand_gaussians import (
    build_brush_centerline,
    DecodedGroom,
    GroomParameterField,
    GroomRanges,
    ResampledStrands,
    StrandGaussianOutput,
    adaptive_resample_strands,
    build_strands,
    decode_positive_asinh,
    decode_positive_asinh_ratio,
    encode_positive_asinh,
    encode_positive_asinh_ratio,
    expand_child_strands,
    make_tangent_frames,
    resample_strands_to_segment_budgets,
    strand_segment_budgets,
    strands_to_gaussians,
)

__all__ = [
    "build_brush_centerline",
    "DecodedGeometryResiduals",
    "DecodedGroom",
    "GroomParameterField",
    "GroomRanges",
    "GaussianRGBResidualField",
    "RenderGeometryResidualField",
    "ResampledStrands",
    "StrandGaussianOutput",
    "adaptive_resample_strands",
    "apply_asinh_logit_residual",
    "apply_asinh_log_ratio_residual",
    "apply_direction_residual",
    "apply_log_ratio_residual",
    "build_strands",
    "decode_positive_asinh",
    "decode_positive_asinh_ratio",
    "direction_to_local_components",
    "expand_child_strands",
    "encode_positive_asinh",
    "encode_positive_asinh_ratio",
    "encode_asinh_logit_residual",
    "fourth_moment_norm",
    "make_tangent_frames",
    "local_components_to_world",
    "length_residual_prior_coordinate",
    "population_stable_residual_norm",
    "tail_concentration_residual_loss",
    "vector_to_local_components",
    "resample_strands_to_segment_budgets",
    "strand_segment_budgets",
    "strands_to_gaussians",
]
