#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="${PROJECT_ROOT:-$(cd "${SCRIPT_DIR}/.." && pwd)}"
export PROJECT_ROOT
cd "$PROJECT_ROOT"

export RUN_NAME="${RUN_NAME:-$(date +%Y%m%d%H%M%S)}"
export SKIP_ORIENTATION_GENERATION="${SKIP_ORIENTATION_GENERATION:-1}"

# Stage 1 is the reconstruction-oriented fur training run. It learns editable
# grooming parameters on the mesh surface. A random colored mesh backing may be
# used only as an anti-transparency training background for white fur; it is not
# the final mesh surface texture layer.
export ROOTS="${ROOTS:-200000}"
export EXTRA_ROOTS="${EXTRA_ROOTS:-80000}"
export EXTRA_ROOT_SOURCE="${EXTRA_ROOT_SOURCE:-head_detail}"
export EXTRA_ROOT_BOOST="${EXTRA_ROOT_BOOST:-4.0}"
export EXTRA_ROOT_GAMMA="${EXTRA_ROOT_GAMMA:-0.75}"
export EXTRA_ROOT_WEIGHT_CAP="${EXTRA_ROOT_WEIGHT_CAP:-0.0}"
export EXTRA_ROOT_BOUNDARY_DILATION="${EXTRA_ROOT_BOUNDARY_DILATION:-17}"
export EXTRA_ROOT_MIN_ORIENT_CONFIDENCE="${EXTRA_ROOT_MIN_ORIENT_CONFIDENCE:-0.04}"
export NO_ROOT_RESIDUAL_BASE="${NO_ROOT_RESIDUAL_BASE:-0}"

export SURFACE_ROOTS="${SURFACE_ROOTS:-120000}"
export SURFACE_ALPHA_SCALE="${SURFACE_ALPHA_SCALE:-0.0}"
export RANDOM_MESH_BACKING_WEIGHT="${RANDOM_MESH_BACKING_WEIGHT:-0.08}"
export RANDOM_MESH_BACKING_START_ITER="${RANDOM_MESH_BACKING_START_ITER:-500}"
export RANDOM_MESH_BACKING_WARMUP_ITERS="${RANDOM_MESH_BACKING_WARMUP_ITERS:-1000}"
export RANDOM_MESH_BACKING_STRENGTH="${RANDOM_MESH_BACKING_STRENGTH:-1.0}"
export RANDOM_MESH_BACKING_ALPHA_SCALE="${RANDOM_MESH_BACKING_ALPHA_SCALE:-0.75}"
export RANDOM_MESH_BACKING_NORMAL_OFFSET="${RANDOM_MESH_BACKING_NORMAL_OFFSET:-0.004}"

export ITERS="${ITERS:-5000}"
export SAVE_EVERY="${SAVE_EVERY:-500}"
export FLOW_ORIENT_WEIGHT="${FLOW_ORIENT_WEIGHT:-0.06}"
export FLOW_ORIENT_END_ITER="${FLOW_ORIENT_END_ITER:-0}"
export FLOW_ORIENT_DECAY_ITERS="${FLOW_ORIENT_DECAY_ITERS:-0}"
export GROOM_GEOMETRY_WEIGHT="${GROOM_GEOMETRY_WEIGHT:-0.5}"

export ROOT_BOUNDARY_BOOST="${ROOT_BOUNDARY_BOOST:-0.50}"
export ROOT_BOUNDARY_GAMMA="${ROOT_BOUNDARY_GAMMA:-0.75}"
export ROOT_BOUNDARY_DILATION="${ROOT_BOUNDARY_DILATION:-17}"

export BOUNDARY_MASK_LOSS_WEIGHT="${BOUNDARY_MASK_LOSS_WEIGHT:-0.0}"
export GROOM_BOUNDARY_LENGTH_BOOST="${GROOM_BOUNDARY_LENGTH_BOOST:-0.04}"
export GROOM_BOUNDARY_DENSITY_FLOOR="${GROOM_BOUNDARY_DENSITY_FLOOR:-0.0}"
export GROOM_BOUNDARY_LIFT_FLOOR="${GROOM_BOUNDARY_LIFT_FLOOR:-0.0}"

bash "$PROJECT_ROOT/scripts/train_white_tiger_uv_groom_server.sh"
